version: '3.8'
services:
  app:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
      - ~/.config/gcloud/application_default_credentials.json:/gcloud/adc.json:ro
    command: sh -c "npm install -g pnpm && pnpm install && pnpm add -w -D depcheck && tail -f /dev/null"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/gcloud/adc.json
    env_file:
      - .env
    ports:
      - "${PORT:-8080}:8080"
      - "${WEB_PORT:-5173}:5173"