name: mobile
description: Flutter Android sample
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  camera: ^0.11.0+2
  google_mlkit_face_detection: ^0.11.1
  image_picker: ^1.1.2
  video_player: ^2.9.2
  video_thumbnail: ^0.5.3
  path_provider: ^2.1.2

flutter:
  uses-material-design: true
